export const SHOP_DATA = [
  {
    id: 1,
    title: "Bestsellers",
    routeName: "bestsellers",
    items: [
      {
        id: 1,
        name: "Versace pour homme",
        imageUrl: "http://unsplash.it/100/100",
        price: "€75",
      },
      {
        id: 2,
        name: "Chanel No.5",
        imageUrl: "http://unsplash.it/100/100",
        price: "€120",
      },
      {
        id: 3,
        name: "DavidOff Cool water",
        imageUrl: "http://unsplash.it/100/100",
        price: "€68",
      },
      {
        id: 4,
        name: "Lancome La vie est belle",
        imageUrl: "http://unsplash.it/100/100",
        price: "€110",
      },
      {
        id: 5,
        name: "Acqua di GIO",
        imageUrl: "http://unsplash.it/100/100",
        price: "€65",
      },
      {
        id: 6,
        name: "YSL Black Opium",
        imageUrl: "http://unsplash.it/100/100",
        price: "€85",
      },
      {
        id: 7,
        name: "Jean Paul Gaultier EDT",
        imageUrl: "http://unsplash.it/100/100",
        price: "€60",
      },
      {
        id: 8,
        name: "D&G Light Blue",
        imageUrl: "http://unsplash.it/100/100",
        price: "€95",
      },
      {
        id: 9,
        name: "1Million Parco Rabanne",
        imageUrl: "http://unsplash.it/100/100",
        price: "€74",
      },
    ],
  },
  {
    id: 2,
    title: "Luxury",
    routeName: "luxury",
    items: [
      {
        id: 10,
        name: "Delina Exclusif",
        imageUrl: "http://unsplash.it/100/100",
        price: "€235",
      },
      {
        id: 11,
        name: "Giorgio Armani",
        imageUrl: "http://unsplash.it/100/100",
        price: "€398",
      },
      {
        id: 12,
        name: "Gris Dior",
        imageUrl: "http://unsplash.it/100/100",
        price: "€307",
      },
      {
        id: 13,
        name: "Guerlains les Exclusifs",
        imageUrl: "http://unsplash.it/100/100",
        price: "€205",
      },
      {
        id: 14,
        name: "Oud Maison",
        imageUrl: "http://unsplash.it/100/100",
        price: "€290",
      },
      {
        id: 15,
        name: "Nike Brown High Tops",
        imageUrl: "http://unsplash.it/100/100",
        price: 160,
      },
      {
        id: 16,
        name: "Air Jordan Limited",
        imageUrl: "http://unsplash.it/100/100",
        price: 190,
      },
      {
        id: 17,
        name: "Timberlands",
        imageUrl: "http://unsplash.it/100/100",
        price: 200,
      },
    ],
  },
  {
    id: 3,
    title: "Budget",
    routeName: "budget",
    items: [
      {
        id: 18,
        name: "Pink Sugar",
        imageUrl: "http://unsplash.it/100/100",
        price: "€20",
      },
      {
        id: 19,
        name: "Midnight Fantasy",
        imageUrl: "http://unsplash.it/100/100",
        price: "€14.5",
      },
      {
        id: 20,
        name: "Reb'l Fleur Rihanna ",
        imageUrl: "http://unsplash.it/100/100",
        price: "€18",
      },
      {
        id: 21,
        name: "Lolita Lempicka",
        imageUrl: "http://unsplash.it/100/100",
        price: "€25",
      },
      {
        id: 22,
        name: "Someday by J.Bieber",
        imageUrl: "http://unsplash.it/100/100",
        price: "€19",
      },
    ],
  },
  {
    id: 4,
    title: "Womens",
    routeName: "womens",
    items: [
      {
        id: 23,
        name: "Chanel Chance",
        imageUrl: "http://unsplash.it/100/100",
        price: 120,
      },
      {
        id: 24,
        name: "Floral Blouse",
        imageUrl: "http://unsplash.it/100/100",
        price: 20,
      },
      {
        id: 25,
        name: "Floral Dress",
        imageUrl: "http://unsplash.it/100/100",
        price: 80,
      },
      {
        id: 26,
        name: "Red Dots Dress",
        imageUrl: "http://unsplash.it/100/100",
        price: 80,
      },
      {
        id: 27,
        name: "Striped Sweater",
        imageUrl: "http://unsplash.it/100/100",
        price: 45,
      },
      {
        id: 28,
        name: "Yellow Track Suit",
        imageUrl: "http://unsplash.it/100/100",
        price: 135,
      },
      {
        id: 29,
        name: "White Blouse",
        imageUrl: "http://unsplash.it/100/100",
        price: 20,
      },
    ],
  },
  {
    id: 5,
    title: "Mens",
    routeName: "mens",
    items: [
      {
        id: 30,
        name: "Dior Sauvage",
        imageUrl: "http://unsplash.it/100/100",
        price: 325,
      },
      {
        id: 31,
        name: "Floral T-shirt",
        imageUrl: "http://unsplash.it/100/100",
        price: 20,
      },
      {
        id: 32,
        name: "Black & White Longsleeve",
        imageUrl: "http://unsplash.it/100/100",
        price: 25,
      },
      {
        id: 33,
        name: "Pink T-shirt",
        imageUrl: "http://unsplash.it/100/100",
        price: 25,
      },
      {
        id: 34,
        name: "Jean Long Sleeve",
        imageUrl: "http://unsplash.it/100/100",
        price: 40,
      },
      {
        id: 35,
        name: "Burgundy T-shirt",
        imageUrl: "http://unsplash.it/100/100",
        price: 25,
      },
    ],
  },
];
